# 发布者配置
publisher:
  protocol: tcp   # 通信方式支持: tcp, ipc, inproc, pgm, epgm等
  ip: 127.0.0.1
  port: 11111     # 远程访问 端口目前默认使用(11111)
  send_timeout: 1000 # 发送超时时间(毫秒) 0: 非阻塞模式，发送失败立即返回; -1: 无限等待，直到发送成功; >0: 指定毫秒数后超时返回
  send_hwm: 1000
  # 发送队列长度(send_hwm)
  #   -1: 无限制
  #   0: 禁用队列
  # >0: 队列中允许的最大消息数
  # 建议值: 根据系统内存和消息大小调整，典型值1000-10000

# 订阅者配置
subscriber:
  protocol: tcp   # 通信方式必须与发布者一致
  ip: 127.0.0.1
  port: 11111     # 远程访问 端口目前默认使用(11111)
  recv_timeout: 1000   # 接收超时时间(毫秒) 0: 非阻塞模式，无消息立即返回; -1: 无限等待，直到收到消息; >0: 指定毫秒数后超时返回
  recv_hwm: 1000
  # 接收队列长度(recv_hwm)
  #   -1: 无限制
  #   0: 禁用队列
  # >0: 队列中允许的最大消息数
  # 建议值: 根据系统内存和消息大小调整，典型值1000-10000