- client_title: "rfid"     # 自定义标题
  ip: "10.10.20.214"      # 监听ip，监听所有网卡使用0.0.0.0
  port: 12345             # 监听端口
  reuse_address: true     # 允许地址复用
  ttl: 1                  # 组播TTL (默认1不能跨子网传播)
  targets: # 目标设置（单播/广播/组播）
    - name: "rfid-location"                      # 自定义通信名称
      type: 1                              # 单播1
      ip: "10.10.20.187"  
      port: 6801
      interface: ""                         # 单播无需指定网卡
#     - name: "jihe"                          # 自定义通信名称
#       type: 2                               # 组播2
#       ip: "224.0.0.100"                     # 组播目标
#       port: 12345
#       interface: "00-E0-97-21-B5-12"        # 组播广播需指定网卡mac地址，例如(00-E0-97-21-B5-12)
#     - name: "jihe1"                         # 自定义通信名称
#       type: 3                              # 广播3
#       ip: "255.255.255.255"                 # 广播目标 当前子网 255.255.255.255不能跨子网
#       port: 54321
#       interface: "00-E0-97-21-B5-12"        # 组播需指定网卡mac地址，例如(00-E0-97-21-B5-12)
- client_title: "jihe"
  ip: "127.0.0.1"
  port: 12346
  reuse_address: true     # 允许地址复用
  ttl: 1                  # 组播TTL (默认1不能跨子网传播)
  targets: # 目标设置（单播/广播/组播）
    - name: "jihe-dwc"                      # 自定义通信名称
      type: 1                              # 单播1
      ip: "10.10.10.10" 
      port: 6801
      interface: ""                         # 单播无需指定网卡

- client_title: "6017udp_0"
  ip: "127.0.0.1"
  port: 2111
  reuse_address: true     # 允许地址复用
  ttl: 1                  # 组播TTL (默认1不能跨子网传播)
# - client_title: "jihe"                      # 自定义标题
#   ip: "127.0.0.1"                           # 监听ip，监听所有网卡使用0.0.0.0
#   port: 12345                               # 监听端口
#   reuse_address: true                       # 允许地址复用
#   ttl: 1                                    # 组播TTL (默认1不能跨子网传播)
#   targets: # 目标设置（单播/广播/组播）
#     - name: "location"                      # 自定义通信名称
#       type: 1                               # 单播1
#       ip: "192.168.1.100"  
#       port: 12345
#       interface: ""                         # 单播无需指定网卡
#     - name: "jihe"                          # 自定义通信名称
#       type: 2                               # 组播2
#       ip: "224.0.0.100"                     # 组播目标
#       port: 12345
#       interface: "00-E0-97-21-B5-12"        # 组播广播需指定网卡mac地址，例如(00-E0-97-21-B5-12)
#     - name: "jihe1"                         # 自定义通信名称
#       type: 3                              # 广播3
#       ip: "255.255.255.255"                 # 广播目标 当前子网 255.255.255.255不能跨子网
#       port: 54321
#       interface: "00-E0-97-21-B5-12"        # 组播需指定网卡mac地址，例如(00-E0-97-21-B5-12)

- client_title: "mvb"                      # 自定义标题
  ip: "0.0.0.0"                           # 监听ip，监听所有网卡使用0.0.0.0
  port: 18000                               # 监听端口
  reuse_address: true                       # 允许地址复用
  ttl: 1                                    # 组播TTL (默认1不能跨子网传播)
  # targets: # 目标设置（单播/广播/组播）
  #   - name: "mvb_heart"                      # 自定义通信名称
  #     type: 1                              # 单播1
  #     ip: "127.0.0.1"  
  #     port: 18001
  #     interface: ""                         # 单播无需指
 
# 1. TTL 的作用
# TTL 的主要功能是：
# 限制组播包的传输范围：防止组播数据在网络中无限循环。
# 控制跨路由器的跳数：每经过一个路由器，TTL 值减 1，当 TTL 降为 0 时，数据包被丢弃。

# 2. TTL 的取值含义
# TTL 值	适用范围	典型场景
# 0	仅限本地主机	数据包不离开发送主机（如测试回环）。
# 1	本地子网（默认值）	局域网内组播（路由器不转发）。
# 2~31	受限范围（组织内跨子网）	企业内网或特定区域组播。
# 32~255	全局范围（跨互联网）	需运营商支持的大范围组播（罕见）。
