hik_info:
  - type: "NORMAL"
    ipaddr: "10.10.10.123"
    port: 8000
    username: "admin"
    password: "Gwkj1234"
    channel: 1  # 相机中的通道号而不是NVR
    camera_name: "camera1"
    camera_gain: 1                      # 增益 暂时不支持
    camera_exposure: 1                  # 曝光 暂时不支持
    camera_fps: 25                      # 帧率 暂时不支持
    camera_roi: [ 0, 0, 1920, 1080 ]    # ROI区域，左上角和右下角坐标  暂时不支持

nvr_info:
  ipaddr: "127.0.0.1"
  port: 8000
  username: "admin"
  password: "Gwkj1234"